function Rotator2dMenu(fig, rotatorLinker)
m = uimenu(fig, "Text", "File");
generateExportResultsMenu(m , rotatorLinker);
end
function generateExportResultsMenu(parentMenu, rotatorLinker)
uimenu(parentMenu, ...
    "Text", "Export", ...
    "MenuSelectedFcn", @rotatorLinker.exportButtonPushed, ...
    "Accelerator", "S" ...
    );
end