function TrackingMenu(fig, trackingLinker)
generateFileMenu(fig, trackingLinker);
generateRegionMenu(fig, trackingLinker);
generatePlottingMenu(fig, trackingLinker);
end

function generateFileMenu(fig, trackingLinker)
m = uimenu(fig, "Text", "File");
generateImportRegionMenu(m, trackingLinker);
generateImportVideoMenu(m, trackingLinker);
generateOpenDirectoryMenu(m, trackingLinker);
end
function generateImportRegionMenu(parentMenu, trackingLinker)
uimenu(parentMenu, ...
    "Text", SettingsParser.getImportRegionsLabel(), ...
    "MenuSelectedFcn", @trackingLinker.importRegionsButtonPushed, ...
    "Accelerator", "R" ...
    );
end
function generateImportVideoMenu(parentMenu, videoSelector)
uimenu(parentMenu, ...
    "Text", SettingsParser.getImportVideoLabel(), ...
    "MenuSelectedFcn", @videoSelector.importVideoButtonPushed, ...
    "Accelerator", "I" ...
    );
end
function generateOpenDirectoryMenu(parentMenu, videoSelector)
uimenu(parentMenu, ...
    "Text", SettingsParser.getOpenDirectoryLabel(), ...
    "MenuSelectedFcn", @videoSelector.openDirectory, ...
    "Accelerator", "O" ...
    );
end

function generateRegionMenu(fig, trackingLinker)
m = uimenu(fig, "Text", "Region");
generateThresholdMenu(m, trackingLinker);
generateBlobDetectionMenu(m, trackingLinker);

end
function generateBlobDetectionMenu(parentMenu, trackingLinker)
uimenu(parentMenu, ...
    "Text", SettingsParser.getBlobDetectionFigureDefaults().Name, ...
    "MenuSelectedFcn", @trackingLinker.blobDetectionButtonPushed ...
    );
end
function generateThresholdMenu(parentMenu, trackingLinker)
uimenu(parentMenu, ...
    "Text", SettingsParser.getAutothresholdFigureDefaults().Name, ...
    "MenuSelectedFcn", @trackingLinker.regionThresholdButtonPushed ...
    );
end

function generatePlottingMenu(fig, trackingLinker)
m = uimenu(fig, "Text", "Analysis");
generateOpenDetrenderMenu(m, trackingLinker);
generateOpenRoiMenu(m, trackingLinker);
generateOpenWaterfallMenu(m, trackingLinker);
generateProbeCalibratorMenu(m, trackingLinker);
end
function generateProbeCalibratorMenu(parentMenu, trackingLinker)
uimenu(parentMenu, ...
    "Text", "Calibrate Probe", ...
    "MenuSelectedFcn", @trackingLinker.openProbeCalibratorPushed ...
    );
end
function generateOpenRoiMenu(parentMenu, trackingLinker)
uimenu(parentMenu, ...
    "Text", "Open ROI Plot", ...
    "MenuSelectedFcn", @trackingLinker.openRoiPlotPushed ...
    );
end
function generateOpenWaterfallMenu(parentMenu, trackingLinker)
uimenu(parentMenu, ...
    "Text", "Open Waterfall Plot", ...
    "MenuSelectedFcn", @trackingLinker.openWaterfallPlotPushed ...
    );
end
function generateOpenDetrenderMenu(parentMenu, trackingLinker)
uimenu(parentMenu, ...
    "Text", "Open Detrender Plot", ...
    "MenuSelectedFcn", @trackingLinker.openDetrenderButtonPushed ...
    );
end
