function DetrenderMenu(fig, detrenderLinker)
m = uimenu(fig, "Text", "File");
generateExportResultsMenu(m , detrenderLinker);
end
function generateExportResultsMenu(parentMenu, detrenderLinker)
uimenu(parentMenu, ...
    "Text", "Export", ...
    "MenuSelectedFcn", @detrenderLinker.exportButtonPushed, ...
    "Accelerator", "S" ...
    );
end