function [regionsCenter, dataPoints] = plotRoiArrow(ax, resultsParser, varargin)
p = inputParser;
addOptional(p, "ArrowLength", 25);
addOptional(p, "IncludePoints", true);
parse(p, varargin{:});
arrowLength = p.Results.ArrowLength;
includePoints = p.Results.IncludePoints;

angles = resultsParser.getAngleRadians();
regionCount = resultsParser.getRegionCount();
regionsCenter = zeros(regionCount, 2);
dataPoints = matlab.graphics.chart.primitive.Scatter.empty(regionCount, 0);

for index = 1:regionCount
    region = resultsParser.getRegion(index);
    regionPosition = region.Position;
    regionCenter = regionPosition(1:2) + 0.5 * regionPosition(3:4);

    angle = -angles(index);
    quiver(ax, ...
        regionCenter(1), ...
        regionCenter(2), ...
        arrowLength * cos(angle), ...
        arrowLength * sin(angle), ...
        "AutoScale", 0, ...
        "Color", "red", ...
        "LineWidth", 1, ...
        "MaxHeadSize", 1 ...
        );

    if includePoints
        dataPoints(index) = scatter(ax, ...
            regionCenter(1), ...
            regionCenter(2), ...
            288, ...
            "filled", ...
            "red", ...
            "MarkerFaceAlpha", 0, ...
            "MarkerEdgeAlpha", 0 ...
            );
    end

    regionsCenter(index, :) = regionCenter;
end
end