classdef TrackingToolbar
    methods
        function obj = TrackingToolbar(fig, regionDrawer)
            toolbar = uitoolbar(fig);
            generateRegionShapeSection(toolbar, regionDrawer);
        end
    end
end



function generateRegionShapeSection(toolbar, regionDrawer)
ellipseIcon = imread("img/ellipse.png");
rectangleIcon = imread("img/rectangle.png");
polygonIcon = imread("img/polygon.png");
freehandIcon = imread("img/freehand.png");

uipushtool(toolbar, ...
    "Icon", ellipseIcon, ...
    "ClickedCallback", @regionDrawer.setEllipseShape ...
    );
uipushtool(toolbar, ...
    "Icon", rectangleIcon, ...
    "ClickedCallback", @regionDrawer.setRectangleShape ...
    );
uipushtool(toolbar, ...
    "Icon", polygonIcon, ...
    "ClickedCallback", @regionDrawer.setPolygonShape ...
    );
uipushtool(toolbar, ...
    "Icon", freehandIcon, ...
    "ClickedCallback", @regionDrawer.setFreehandShape ...
    );
end
