function tools = generateExplorerTools(toolbar, trackingLinker)
videoSelector = trackingLinker.getVideoSelector();
saveImageTool = generateSaveImageTool(toolbar, trackingLinker);
importVideoTool = generateImportVideoTool(toolbar, videoSelector);
openDirectoryTool = generateOpenDirectoryTool(toolbar, videoSelector);
tools = [saveImageTool, importVideoTool, openDirectoryTool];
end

function tool = generateSaveImageTool(toolbar, trackingLinker)
[icon, ~, ~] = imread("img/image.png");
tool = uipushtool(toolbar, ...
    "Icon", icon, ...
    "ClickedCallback", @trackingLinker.exportImageIfPossible, ...
    "Tooltip", AxisExporter.title + " (Ctrl+S)" ...
    );
end

function tool = generateImportVideoTool(toolbar, videoSelector)
[icon, ~, ~] = imread("img/folder-open.png");
tool = uipushtool(toolbar, ...
    "Icon", icon, ...
    "ClickedCallback", @videoSelector.importVideo, ...
    "Tooltip", VideoSelector.importTitle + " (Ctrl+I)" ...
    );
end

function tool = generateOpenDirectoryTool(toolbar, videoSelector)
[icon, ~, ~] = imread("img/desktop.png");
tool = uipushtool(toolbar, ...
    "Icon", icon, ...
    "ClickedCallback", @videoSelector.openDirectory, ...
    "Tooltip", VideoSelector.openTitle + " (Ctrl+O)" ...
    );
end
