function tools = generateRegionShapeTools(toolbar)
rectangleTool = generateRectangleTool(toolbar);
ellipseTool = generateEllipseTool(toolbar);
polygonTool = generatePolygonTool(toolbar);
freehandTool = generateFreehandTool(toolbar);
tools = [rectangleTool, ellipseTool, polygonTool, freehandTool];
end

function tool = generateRectangleTool(toolbar)
icon = imread("img/rectangle.png");
keyword = RegionDrawer.rectangleKeyword;
tool = uitoggletool(toolbar, ...
    "Icon", icon, ...
    "UserData", keyword, ...
    "Tooltip", "Draw Rectangle" ...
    );
end

function tool = generateEllipseTool(toolbar)
icon = imread("img/ellipse.png");
keyword = RegionDrawer.ellipseKeyword;
tool = uitoggletool(toolbar, ...
    "Icon", icon, ...
    "UserData", keyword, ...
    "Tooltip", "Draw Ellipse" ...
    );
end

function tool = generatePolygonTool(toolbar)
icon = imread("img/polygon.png");
keyword = RegionDrawer.polygonKeyword;
tool = uitoggletool(toolbar, ...
    "Icon", icon, ...
    "UserData", keyword, ...
    "Tooltip", "Draw Polygon" ...
    );
end

function tool = generateFreehandTool(toolbar)
icon = imread("img/freehand.png");
keyword = RegionDrawer.freehandKeyword;
tool = uitoggletool(toolbar, ...
    "Icon", icon, ...
    "UserData", keyword, ...
    "Tooltip", "Draw Freehand" ...
    );
end
