function tools = generateRegionOrderTools(toolbar, trackingLinker)
previousRegionTool = generatePreviousRegionTool(toolbar, trackingLinker);
nextRegionTool = generateNextRegionTool(toolbar, trackingLinker);
bringToFrontTool = generateBringRegionToFrontTool(toolbar, trackingLinker);
sendToBackTool = generateSendRegionToBackTool(toolbar, trackingLinker);
bringForwardTool = generateBringRegionForwardTool(toolbar, trackingLinker);
sendBackwardTool = generateSendRegionBackwardTool(toolbar, trackingLinker);
tools = [
    previousRegionTool, ...
    nextRegionTool, ...
    bringToFrontTool, ...
    sendToBackTool ...
    bringForwardTool, ...
    sendBackwardTool, ...
    ];
end

function tool = generatePreviousRegionTool(toolbar, trackingLinker)
[leftChevron, ~, ~] = imread("img/caret-left.png");
tool = uipushtool(toolbar, ...
    "Icon", leftChevron, ...
    "ClickedCallback", @trackingLinker.setPreviousRegionVisible, ...
    "Tooltip", "Select Previous Region (Alt+←)" ...
    );
end

function tool = generateNextRegionTool(toolbar, trackingLinker)
[rightChevron, ~, ~] = imread("img/caret-right.png");
tool = uipushtool(toolbar, ...
    "Icon", rightChevron, ...
    "ClickedCallback", @trackingLinker.setNextRegionVisible, ...
    "Tooltip", "Select Next Region (Alt+→)" ...
    );
end

function tool = generateBringRegionToFrontTool(toolbar, trackingLinker)
[icon, ~, ~] = imread("img/bring-to-front.png");
tool = uipushtool(toolbar, ...
    "Icon", icon, ...
    "ClickedCallback", @trackingLinker.bringRegionToFront, ...
    "Tooltip", "Bring Region to Front (Ctrl+Shift+Alt+↑)" ...
    );
end

function tool = generateBringRegionForwardTool(toolbar, trackingLinker)
[icon, ~, ~] = imread("img/bring-forward.png");
tool = uipushtool(toolbar, ...
    "Icon", icon, ...
    "ClickedCallback", @trackingLinker.bringRegionForward, ...
    "Tooltip", "Bring Region Forward (Alt+↑)" ...
    );
end

function tool = generateSendRegionBackwardTool(toolbar, trackingLinker)
[icon, ~, ~] = imread("img/send-backward.png");
tool = uipushtool(toolbar, ...
    "Icon", icon, ...
    "ClickedCallback", @trackingLinker.sendRegionBackward, ...
    "Tooltip", "Send Region Backward (Alt+↓)" ...
    );
end

function tool = generateSendRegionToBackTool(toolbar, trackingLinker)
[icon, ~, ~] = imread("img/send-to-back.png");
tool = uipushtool(toolbar, ...
    "Icon", icon, ...
    "ClickedCallback", @trackingLinker.sendRegionToBack, ...
    "Tooltip", "Send Region to Back (Ctrl+Shift+Alt+↓)" ...
    );
end
