function tools = generateWebsiteTools(toolbar)
labWebsiteTool = generateLabWebsiteTool(toolbar);
githubTool = generateGithubTool(toolbar);
tools = [labWebsiteTool, githubTool];
end

function tool = generateLabWebsiteTool(toolbar)
[frogIcon, ~, ~] = imread("img/frog.png");
url = "https://bozoviclab.physics.ucla.edu";
tool = uipushtool(toolbar, ...
    "Icon", frogIcon, ...
    "ClickedCallback", @(src, ev) web(url), ...
    "Tooltip", "Open Bozovic Lab Website" ...
    );
end

function tool = generateGithubTool(toolbar)
[githubIcon, ~, ~] = imread("img/github-logo.png");
url = "https://github.com/jmarcinik3/BundleTracker";
tool = uipushtool(toolbar, ...
    "Icon", githubIcon, ...
    "ClickedCallback", @(src, ev) web(url), ...
    "Tooltip", "Open GitHub" ...
    );
end
