function TrackingMenu(fig, trackingLinker)
m = uimenu(fig, "Text", "Region");
generateBatchMenu(m, trackingLinker);
end



function generateBatchMenu(m, trackingLinker)
uimenu(m, ...
    "Text", OtsuThresholdsGui.title, ...
    "MenuSelectedFcn", @trackingLinker.otsuThresholdsPushed ...
    );
uimenu(m, ...
    "Text", AutoThresholdGui.title, ...
    "MenuSelectedFcn", @trackingLinker.regionThresholdButtonPushed ...
    );
uimenu(m, ...
    "Text", BlobDetectorGui.title, ...
    "MenuSelectedFcn", @trackingLinker.blobDetectionButtonPushed ...
    );
end

