function generateFileMenu(fig, trackingLinker)
m = uimenu(fig, "Text", "File");
generateSaveImageMenu(m, trackingLinker);
generateImportVideoMenu(m, trackingLinker);
generateImportRegionMenu(m, trackingLinker);
generateOpenDirectoryMenu(m, trackingLinker);
end

function generateImportRegionMenu(parentMenu, trackingLinker)
text = SettingsParser.getImportRegionsLabel();
uimenu(parentMenu, ...
    "Text", text, ...
    "MenuSelectedFcn", @trackingLinker.importRegionsMenuCalled, ...
    "Accelerator", "R" ...
    );
end

function generateSaveImageMenu(parentMenu, trackingLinker)
text = SettingsParser.getExportAxisLabel();
uimenu(parentMenu, ...
    "Text", text, ...
    "MenuSelectedFcn", @trackingLinker.exportImageIfPossible, ...
    "Accelerator", "S" ...
    );
end

function generateImportVideoMenu(parentMenu, videoSelector)
text = SettingsParser.getImportVideoLabel();
uimenu(parentMenu, ...
    "Text", text, ...
    "MenuSelectedFcn", @videoSelector.openDirectory, ...
    "Accelerator", "O" ...
    );
end

function generateOpenDirectoryMenu(parentMenu, videoSelector)
text = SettingsParser.getOpenDirectoryLabel();
uimenu(parentMenu, ...
    "Text", text, ...
    "MenuSelectedFcn", @videoSelector.importVideo, ...
    "Accelerator", "I" ...
    );
end
