function generateFileMenu(fig, trackingLinker)
m = uimenu(fig, "Text", "File");
generateSaveImageMenu(m, trackingLinker);
generateImportVideoMenu(m, trackingLinker);
generateOpenDirectoryMenu(m, trackingLinker);
end

function generateSaveImageMenu(parentMenu, trackingLinker)
uimenu(parentMenu, ...
    "Text", AxisExporter.title, ...
    "MenuSelectedFcn", @trackingLinker.exportImageIfPossible, ...
    "Accelerator", "S" ...
    );
end

function generateImportVideoMenu(parentMenu, videoSelector)
uimenu(parentMenu, ...
    "Text", VideoSelector.openTitle, ...
    "MenuSelectedFcn", @videoSelector.openDirectory, ...
    "Accelerator", "O" ...
    );
end

function generateOpenDirectoryMenu(parentMenu, videoSelector)
uimenu(parentMenu, ...
    "Text", VideoSelector.importTitle, ...
    "MenuSelectedFcn", @videoSelector.importVideo, ...
    "Accelerator", "I" ......
    );
end
