function result = appendRegionMetadata(result, region)
if RegionType.isRectangle(region)
    result = appendRectangleMetadata(result, region);
elseif RegionType.isEllipse(region)
    result = appendEllipseMetadata(result, region);
elseif RegionType.isPolygon(region)
    result = appendPolygonMetadata(result, region);
elseif RegionType.isFreehand(region)
    result = appendFreehandMetadata(result, region);
end
end

function result = appendRectangleMetadata(result, rect)
result.Region = struct( ...
    "Type", rect.Type, ...
    "Position", rect.Position, ...
    "Rotatable", rect.Rotatable ...
    );
end

function result = appendEllipseMetadata(result, ell)
result.Region = struct( ...
    "Type", ell.Type, ...
    "Center", ell.Center, ...
    "SemiAxes", ell.SemiAxes, ...
    "RotationAngle", ell.RotationAngle ...
    );
end

function result = appendPolygonMetadata(result, polygon)
result.Region = struct( ...
    "Type", polygon.Type, ...
    "Position", polygon.Position ...
    );
end

function result = appendFreehandMetadata(result, freehand)
result.Region = struct( ...
    "Type", freehand.Type, ...
    "Position", freehand.Position, ...
    "Waypoints", freehand.Waypoints ...
    );
end
