function meta = getRegionMetadata(region)
if RegionType.isRectangle(region)
    meta = appendRectangleMetadata(region);
elseif RegionType.isEllipse(region)
    meta = appendEllipseMetadata(region);
elseif RegionType.isPolygon(region)
    meta = appendPolygonMetadata(region);
elseif RegionType.isFreehand(region)
    meta = appendFreehandMetadata(region);
end
end

function meta = appendRectangleMetadata(rect)
meta = struct( ...
    "Type", rect.Type, ...
    "Position", rect.Position, ...
    "Rotatable", rect.Rotatable ...
    );
end

function meta = appendEllipseMetadata(ell)
meta = struct( ...
    "Type", ell.Type, ...
    "Center", ell.Center, ...
    "SemiAxes", ell.SemiAxes, ...
    "RotationAngle", ell.RotationAngle ...
    );
end

function meta = appendPolygonMetadata(polygon)
meta = struct( ...
    "Type", polygon.Type, ...
    "Position", polygon.Position ...
    );
end

function meta = appendFreehandMetadata(freehand)
meta = struct( ...
    "Type", freehand.Type, ...
    "Position", freehand.Position, ...
    "Waypoints", freehand.Waypoints ...
    );
end
