function meta = getRegionMetadata(region)
if strcmpi(region.Type, "images.roi.rectangle")
    meta = appendRectangleMetadata(region);
elseif strcmpi(region.Type, "images.roi.ellipse")
    meta = appendEllipseMetadata(region);
elseif strcmpi(region.Type, "images.roi.polygon")
    meta = appendPolygonMetadata(region);
elseif strcmpi(region.Type, "images.roi.freehand")
    meta = appendFreehandMetadata(region);
end
end

function meta = appendRectangleMetadata(rect)
meta = struct( ...
    "Type", rect.Type, ...
    "Position", rect.Position, ...
    "Rotatable", rect.Rotatable ...
    );
end

function meta = appendEllipseMetadata(ell)
meta = struct( ...
    "Type", ell.Type, ...
    "Center", ell.Center, ...
    "SemiAxes", ell.SemiAxes, ...
    "RotationAngle", ell.RotationAngle ...
    );
end

function meta = appendPolygonMetadata(polygon)
meta = struct( ...
    "Type", polygon.Type, ...
    "Position", polygon.Position ...
    );
end

function meta = appendFreehandMetadata(freehand)
meta = struct( ...
    "Type", freehand.Type, ...
    "Position", freehand.Position, ...
    "Waypoints", freehand.Waypoints ...
    );
end
