% Generate animator from results file
resultsParser = ResultsParser("Demos/results.mat");
timeSeconds = resultsParser.getTime();
x = resultsParser.getProcessedTrace(1);
ax = gca;
animator = AxisTraceAnimator( ...
    ax, ...
    timeSeconds, ...
    x, ...
    "PlaybackSpeed", 0.1, ...
    "PlaybackFps", 30 ...
    );

% Plot interactive scalebar on axis (optional)
AxisScalebar(animator.getAxis(), ...
    "ScalebarPosition", [0, 0], ...
    "Color", "black", ...
    "Border", 'LL', ...
    "HorizontalUnit", 'ms', ...
    "VerticalUnit", 'nm', ...
    "HorizontalLength", 0.2, ...
    "VerticalLength", 10, ...
    "HorizontalMultiplier", 1e3, ...
    "VerticalMultiplier", 1, ...
    "HorizontalTextPosition", [0, 0], ...
    "VerticalTextPosition", [0, 0], ...
    "HorizontalTextRotation", 0, ...
    "VerticalTextRotation", 90 ...
    );

% Set aesthetics for figure, line, and axis (optional)
set( ...
    animator.getFigure(), ...
    "Color", "white" ...
    );
set( ...
    animator.getAnimatedLine(), ...
    "Color", "black", ...
    "LineStyle", '-', ...
    "LineWidth", 0.5, ...
    "Marker", "none", ...
    "MarkerSize", 6, ...
    "MarkerEdgeColor", "auto", ...
    "MarkerFaceColor", "none" ...
    );
set( ...
    animator.getAxis(), ...
    "XLim", [timeSeconds(1), timeSeconds(end)], ...
    "YLim", [min(x), max(x)], ...
    "Position", [0.05, 0.05, 0.9, 0.9], ...
    "Visible", "on", ...
    "Clipping", "off" ...
    );

% Start animation on startup (optional)
animator.startAnimation();
